---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::hifiasm=0.25.0
  - bioconda::htslib=1.22.1
  - bioconda::samtools=1.22.1
  - conda-forge::gawk=5.3.1
