# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/modules/environment-schema.json
---
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib=1.22.1
  - bioconda::minimap2=2.30
  - bioconda::samtools=1.22.1
  - conda-forge::gawk=5.3.1
  - conda-forge::perl=5.32.1
